// Code generated by Kitex v0.16.1. DO NOT EDIT.

package personaapiservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	karpo_persona "github.com/machinepulse-ai/kitex-karpo-persona/kitex_gen/karpo_persona"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	HealthCheck(ctx context.Context, Req *karpo_persona.PersonaApiHealthCheckReq, callOptions ...callopt.Option) (r *karpo_persona.PersonaApiHealthCheckResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPersonaApiServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPersonaApiServiceClient struct {
	*kClient
}

func (p *kPersonaApiServiceClient) HealthCheck(ctx context.Context, Req *karpo_persona.PersonaApiHealthCheckReq, callOptions ...callopt.Option) (r *karpo_persona.PersonaApiHealthCheckResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HealthCheck(ctx, Req)
}
