// Code generated by Kitex v0.16.1. DO NOT EDIT.

package personaapiservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	karpo_persona "github.com/machinepulse-ai/kitex-karpo-persona/kitex_gen/karpo_persona"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"HealthCheck": kitex.NewMethodInfo(
		healthCheckHandler,
		newHealthCheckArgs,
		newHealthCheckResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	personaApiServiceServiceInfo                = NewServiceInfo()
	personaApiServiceServiceInfoForClient       = NewServiceInfoForClient()
	personaApiServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return personaApiServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return personaApiServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return personaApiServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PersonaApiService"
	handlerType := (*karpo_persona.PersonaApiService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "karpo_persona",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func healthCheckHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.PersonaApiHealthCheckReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaApiService).HealthCheck(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *HealthCheckArgs:
		success, err := handler.(karpo_persona.PersonaApiService).HealthCheck(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*HealthCheckResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newHealthCheckArgs() interface{} {
	return &HealthCheckArgs{}
}

func newHealthCheckResult() interface{} {
	return &HealthCheckResult{}
}

type HealthCheckArgs struct {
	Req *karpo_persona.PersonaApiHealthCheckReq
}

func (p *HealthCheckArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *HealthCheckArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.PersonaApiHealthCheckReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var HealthCheckArgs_Req_DEFAULT *karpo_persona.PersonaApiHealthCheckReq

func (p *HealthCheckArgs) GetReq() *karpo_persona.PersonaApiHealthCheckReq {
	if !p.IsSetReq() {
		return HealthCheckArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *HealthCheckArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *HealthCheckArgs) GetFirstArgument() interface{} {
	return p.Req
}

type HealthCheckResult struct {
	Success *karpo_persona.PersonaApiHealthCheckResp
}

var HealthCheckResult_Success_DEFAULT *karpo_persona.PersonaApiHealthCheckResp

func (p *HealthCheckResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *HealthCheckResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.PersonaApiHealthCheckResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *HealthCheckResult) GetSuccess() *karpo_persona.PersonaApiHealthCheckResp {
	if !p.IsSetSuccess() {
		return HealthCheckResult_Success_DEFAULT
	}
	return p.Success
}

func (p *HealthCheckResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.PersonaApiHealthCheckResp)
}

func (p *HealthCheckResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HealthCheckResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) HealthCheck(ctx context.Context, Req *karpo_persona.PersonaApiHealthCheckReq) (r *karpo_persona.PersonaApiHealthCheckResp, err error) {
	var _args HealthCheckArgs
	_args.Req = Req
	var _result HealthCheckResult
	if err = p.c.Call(ctx, "HealthCheck", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
