// Code generated by Kitex v0.16.1. DO NOT EDIT.
package personaapiservice

import (
	server "github.com/cloudwego/kitex/server"
	karpo_persona "github.com/machinepulse-ai/kitex-karpo-persona/kitex_gen/karpo_persona"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler karpo_persona.PersonaApiService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler karpo_persona.PersonaApiService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
