// Code generated by Kitex v0.16.1. DO NOT EDIT.

package persona_engine_service

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	karpo_persona "github.com/machinepulse-ai/kitex-karpo-persona/kitex_gen/karpo_persona"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	HealthCheck(ctx context.Context, Req *karpo_persona.HealthCheckRequest, callOptions ...callopt.Option) (r *karpo_persona.HealthCheckResponse, err error)
	Absorb(ctx context.Context, Req *karpo_persona.AbsorbRequest, callOptions ...callopt.Option) (r *karpo_persona.AbsorbResponse, err error)
	Recall(ctx context.Context, Req *karpo_persona.RecallRequest, callOptions ...callopt.Option) (r *karpo_persona.RecallResponse, err error)
	GetUserCategories(ctx context.Context, Req *karpo_persona.GetUserCategoriesRequest, callOptions ...callopt.Option) (r *karpo_persona.GetUserCategoriesResponse, err error)
	GetUserGraph(ctx context.Context, Req *karpo_persona.GetUserGraphRequest, callOptions ...callopt.Option) (r *karpo_persona.GetUserGraphResponse, err error)
	TestPipeline(ctx context.Context, Req *karpo_persona.TestPipelineRequest, callOptions ...callopt.Option) (r *karpo_persona.TestPipelineResponse, err error)
	GetRecords(ctx context.Context, Req *karpo_persona.GetRecordsRequest, callOptions ...callopt.Option) (r *karpo_persona.GetRecordsResponse, err error)
	SearchRecords(ctx context.Context, Req *karpo_persona.SearchRecordsRequest, callOptions ...callopt.Option) (r *karpo_persona.SearchRecordsResponse, err error)
	GetRecordSources(ctx context.Context, Req *karpo_persona.GetRecordSourcesRequest, callOptions ...callopt.Option) (r *karpo_persona.GetRecordSourcesResponse, err error)
	GetRecordHistory(ctx context.Context, Req *karpo_persona.GetRecordHistoryRequest, callOptions ...callopt.Option) (r *karpo_persona.GetRecordHistoryResponse, err error)
	GetUserStats(ctx context.Context, Req *karpo_persona.GetUserStatsRequest, callOptions ...callopt.Option) (r *karpo_persona.GetUserStatsResponse, err error)
	ProvisionUser(ctx context.Context, Req *karpo_persona.ProvisionUserRequest, callOptions ...callopt.Option) (r *karpo_persona.ProvisionUserResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPersonaEngineServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPersonaEngineServiceClient struct {
	*kClient
}

func (p *kPersonaEngineServiceClient) HealthCheck(ctx context.Context, Req *karpo_persona.HealthCheckRequest, callOptions ...callopt.Option) (r *karpo_persona.HealthCheckResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HealthCheck(ctx, Req)
}

func (p *kPersonaEngineServiceClient) Absorb(ctx context.Context, Req *karpo_persona.AbsorbRequest, callOptions ...callopt.Option) (r *karpo_persona.AbsorbResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Absorb(ctx, Req)
}

func (p *kPersonaEngineServiceClient) Recall(ctx context.Context, Req *karpo_persona.RecallRequest, callOptions ...callopt.Option) (r *karpo_persona.RecallResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Recall(ctx, Req)
}

func (p *kPersonaEngineServiceClient) GetUserCategories(ctx context.Context, Req *karpo_persona.GetUserCategoriesRequest, callOptions ...callopt.Option) (r *karpo_persona.GetUserCategoriesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserCategories(ctx, Req)
}

func (p *kPersonaEngineServiceClient) GetUserGraph(ctx context.Context, Req *karpo_persona.GetUserGraphRequest, callOptions ...callopt.Option) (r *karpo_persona.GetUserGraphResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserGraph(ctx, Req)
}

func (p *kPersonaEngineServiceClient) TestPipeline(ctx context.Context, Req *karpo_persona.TestPipelineRequest, callOptions ...callopt.Option) (r *karpo_persona.TestPipelineResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TestPipeline(ctx, Req)
}

func (p *kPersonaEngineServiceClient) GetRecords(ctx context.Context, Req *karpo_persona.GetRecordsRequest, callOptions ...callopt.Option) (r *karpo_persona.GetRecordsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecords(ctx, Req)
}

func (p *kPersonaEngineServiceClient) SearchRecords(ctx context.Context, Req *karpo_persona.SearchRecordsRequest, callOptions ...callopt.Option) (r *karpo_persona.SearchRecordsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchRecords(ctx, Req)
}

func (p *kPersonaEngineServiceClient) GetRecordSources(ctx context.Context, Req *karpo_persona.GetRecordSourcesRequest, callOptions ...callopt.Option) (r *karpo_persona.GetRecordSourcesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecordSources(ctx, Req)
}

func (p *kPersonaEngineServiceClient) GetRecordHistory(ctx context.Context, Req *karpo_persona.GetRecordHistoryRequest, callOptions ...callopt.Option) (r *karpo_persona.GetRecordHistoryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecordHistory(ctx, Req)
}

func (p *kPersonaEngineServiceClient) GetUserStats(ctx context.Context, Req *karpo_persona.GetUserStatsRequest, callOptions ...callopt.Option) (r *karpo_persona.GetUserStatsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserStats(ctx, Req)
}

func (p *kPersonaEngineServiceClient) ProvisionUser(ctx context.Context, Req *karpo_persona.ProvisionUserRequest, callOptions ...callopt.Option) (r *karpo_persona.ProvisionUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ProvisionUser(ctx, Req)
}
