// Code generated by Kitex v0.16.1. DO NOT EDIT.

package persona_engine_service

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	karpo_persona "github.com/machinepulse-ai/kitex-karpo-persona/kitex_gen/karpo_persona"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"HealthCheck": kitex.NewMethodInfo(
		healthCheckHandler,
		newHealthCheckArgs,
		newHealthCheckResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Absorb": kitex.NewMethodInfo(
		absorbHandler,
		newAbsorbArgs,
		newAbsorbResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Recall": kitex.NewMethodInfo(
		recallHandler,
		newRecallArgs,
		newRecallResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserCategories": kitex.NewMethodInfo(
		getUserCategoriesHandler,
		newGetUserCategoriesArgs,
		newGetUserCategoriesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserGraph": kitex.NewMethodInfo(
		getUserGraphHandler,
		newGetUserGraphArgs,
		newGetUserGraphResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"TestPipeline": kitex.NewMethodInfo(
		testPipelineHandler,
		newTestPipelineArgs,
		newTestPipelineResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetRecords": kitex.NewMethodInfo(
		getRecordsHandler,
		newGetRecordsArgs,
		newGetRecordsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SearchRecords": kitex.NewMethodInfo(
		searchRecordsHandler,
		newSearchRecordsArgs,
		newSearchRecordsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetRecordSources": kitex.NewMethodInfo(
		getRecordSourcesHandler,
		newGetRecordSourcesArgs,
		newGetRecordSourcesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetRecordHistory": kitex.NewMethodInfo(
		getRecordHistoryHandler,
		newGetRecordHistoryArgs,
		newGetRecordHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserStats": kitex.NewMethodInfo(
		getUserStatsHandler,
		newGetUserStatsArgs,
		newGetUserStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ProvisionUser": kitex.NewMethodInfo(
		provisionUserHandler,
		newProvisionUserArgs,
		newProvisionUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	personaEngineServiceServiceInfo                = NewServiceInfo()
	personaEngineServiceServiceInfoForClient       = NewServiceInfoForClient()
	personaEngineServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return personaEngineServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return personaEngineServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return personaEngineServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PersonaEngineService"
	handlerType := (*karpo_persona.PersonaEngineService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "karpo_persona",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func healthCheckHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.HealthCheckRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaEngineService).HealthCheck(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *HealthCheckArgs:
		success, err := handler.(karpo_persona.PersonaEngineService).HealthCheck(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*HealthCheckResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newHealthCheckArgs() interface{} {
	return &HealthCheckArgs{}
}

func newHealthCheckResult() interface{} {
	return &HealthCheckResult{}
}

type HealthCheckArgs struct {
	Req *karpo_persona.HealthCheckRequest
}

func (p *HealthCheckArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *HealthCheckArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.HealthCheckRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var HealthCheckArgs_Req_DEFAULT *karpo_persona.HealthCheckRequest

func (p *HealthCheckArgs) GetReq() *karpo_persona.HealthCheckRequest {
	if !p.IsSetReq() {
		return HealthCheckArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *HealthCheckArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *HealthCheckArgs) GetFirstArgument() interface{} {
	return p.Req
}

type HealthCheckResult struct {
	Success *karpo_persona.HealthCheckResponse
}

var HealthCheckResult_Success_DEFAULT *karpo_persona.HealthCheckResponse

func (p *HealthCheckResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *HealthCheckResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.HealthCheckResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *HealthCheckResult) GetSuccess() *karpo_persona.HealthCheckResponse {
	if !p.IsSetSuccess() {
		return HealthCheckResult_Success_DEFAULT
	}
	return p.Success
}

func (p *HealthCheckResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.HealthCheckResponse)
}

func (p *HealthCheckResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HealthCheckResult) GetResult() interface{} {
	return p.Success
}

func absorbHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.AbsorbRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaEngineService).Absorb(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AbsorbArgs:
		success, err := handler.(karpo_persona.PersonaEngineService).Absorb(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AbsorbResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAbsorbArgs() interface{} {
	return &AbsorbArgs{}
}

func newAbsorbResult() interface{} {
	return &AbsorbResult{}
}

type AbsorbArgs struct {
	Req *karpo_persona.AbsorbRequest
}

func (p *AbsorbArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AbsorbArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.AbsorbRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AbsorbArgs_Req_DEFAULT *karpo_persona.AbsorbRequest

func (p *AbsorbArgs) GetReq() *karpo_persona.AbsorbRequest {
	if !p.IsSetReq() {
		return AbsorbArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AbsorbArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AbsorbArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AbsorbResult struct {
	Success *karpo_persona.AbsorbResponse
}

var AbsorbResult_Success_DEFAULT *karpo_persona.AbsorbResponse

func (p *AbsorbResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AbsorbResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.AbsorbResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AbsorbResult) GetSuccess() *karpo_persona.AbsorbResponse {
	if !p.IsSetSuccess() {
		return AbsorbResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AbsorbResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.AbsorbResponse)
}

func (p *AbsorbResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AbsorbResult) GetResult() interface{} {
	return p.Success
}

func recallHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.RecallRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaEngineService).Recall(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RecallArgs:
		success, err := handler.(karpo_persona.PersonaEngineService).Recall(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RecallResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRecallArgs() interface{} {
	return &RecallArgs{}
}

func newRecallResult() interface{} {
	return &RecallResult{}
}

type RecallArgs struct {
	Req *karpo_persona.RecallRequest
}

func (p *RecallArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RecallArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.RecallRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RecallArgs_Req_DEFAULT *karpo_persona.RecallRequest

func (p *RecallArgs) GetReq() *karpo_persona.RecallRequest {
	if !p.IsSetReq() {
		return RecallArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RecallArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecallArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RecallResult struct {
	Success *karpo_persona.RecallResponse
}

var RecallResult_Success_DEFAULT *karpo_persona.RecallResponse

func (p *RecallResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RecallResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.RecallResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RecallResult) GetSuccess() *karpo_persona.RecallResponse {
	if !p.IsSetSuccess() {
		return RecallResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RecallResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.RecallResponse)
}

func (p *RecallResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecallResult) GetResult() interface{} {
	return p.Success
}

func getUserCategoriesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.GetUserCategoriesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaEngineService).GetUserCategories(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserCategoriesArgs:
		success, err := handler.(karpo_persona.PersonaEngineService).GetUserCategories(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserCategoriesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserCategoriesArgs() interface{} {
	return &GetUserCategoriesArgs{}
}

func newGetUserCategoriesResult() interface{} {
	return &GetUserCategoriesResult{}
}

type GetUserCategoriesArgs struct {
	Req *karpo_persona.GetUserCategoriesRequest
}

func (p *GetUserCategoriesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserCategoriesArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.GetUserCategoriesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserCategoriesArgs_Req_DEFAULT *karpo_persona.GetUserCategoriesRequest

func (p *GetUserCategoriesArgs) GetReq() *karpo_persona.GetUserCategoriesRequest {
	if !p.IsSetReq() {
		return GetUserCategoriesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserCategoriesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserCategoriesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserCategoriesResult struct {
	Success *karpo_persona.GetUserCategoriesResponse
}

var GetUserCategoriesResult_Success_DEFAULT *karpo_persona.GetUserCategoriesResponse

func (p *GetUserCategoriesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserCategoriesResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.GetUserCategoriesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserCategoriesResult) GetSuccess() *karpo_persona.GetUserCategoriesResponse {
	if !p.IsSetSuccess() {
		return GetUserCategoriesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserCategoriesResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.GetUserCategoriesResponse)
}

func (p *GetUserCategoriesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserCategoriesResult) GetResult() interface{} {
	return p.Success
}

func getUserGraphHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.GetUserGraphRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaEngineService).GetUserGraph(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserGraphArgs:
		success, err := handler.(karpo_persona.PersonaEngineService).GetUserGraph(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserGraphResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserGraphArgs() interface{} {
	return &GetUserGraphArgs{}
}

func newGetUserGraphResult() interface{} {
	return &GetUserGraphResult{}
}

type GetUserGraphArgs struct {
	Req *karpo_persona.GetUserGraphRequest
}

func (p *GetUserGraphArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserGraphArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.GetUserGraphRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserGraphArgs_Req_DEFAULT *karpo_persona.GetUserGraphRequest

func (p *GetUserGraphArgs) GetReq() *karpo_persona.GetUserGraphRequest {
	if !p.IsSetReq() {
		return GetUserGraphArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserGraphArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserGraphArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserGraphResult struct {
	Success *karpo_persona.GetUserGraphResponse
}

var GetUserGraphResult_Success_DEFAULT *karpo_persona.GetUserGraphResponse

func (p *GetUserGraphResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserGraphResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.GetUserGraphResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserGraphResult) GetSuccess() *karpo_persona.GetUserGraphResponse {
	if !p.IsSetSuccess() {
		return GetUserGraphResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserGraphResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.GetUserGraphResponse)
}

func (p *GetUserGraphResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserGraphResult) GetResult() interface{} {
	return p.Success
}

func testPipelineHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.TestPipelineRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaEngineService).TestPipeline(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *TestPipelineArgs:
		success, err := handler.(karpo_persona.PersonaEngineService).TestPipeline(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*TestPipelineResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newTestPipelineArgs() interface{} {
	return &TestPipelineArgs{}
}

func newTestPipelineResult() interface{} {
	return &TestPipelineResult{}
}

type TestPipelineArgs struct {
	Req *karpo_persona.TestPipelineRequest
}

func (p *TestPipelineArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *TestPipelineArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.TestPipelineRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var TestPipelineArgs_Req_DEFAULT *karpo_persona.TestPipelineRequest

func (p *TestPipelineArgs) GetReq() *karpo_persona.TestPipelineRequest {
	if !p.IsSetReq() {
		return TestPipelineArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *TestPipelineArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TestPipelineArgs) GetFirstArgument() interface{} {
	return p.Req
}

type TestPipelineResult struct {
	Success *karpo_persona.TestPipelineResponse
}

var TestPipelineResult_Success_DEFAULT *karpo_persona.TestPipelineResponse

func (p *TestPipelineResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *TestPipelineResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.TestPipelineResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *TestPipelineResult) GetSuccess() *karpo_persona.TestPipelineResponse {
	if !p.IsSetSuccess() {
		return TestPipelineResult_Success_DEFAULT
	}
	return p.Success
}

func (p *TestPipelineResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.TestPipelineResponse)
}

func (p *TestPipelineResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TestPipelineResult) GetResult() interface{} {
	return p.Success
}

func getRecordsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.GetRecordsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaEngineService).GetRecords(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetRecordsArgs:
		success, err := handler.(karpo_persona.PersonaEngineService).GetRecords(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetRecordsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetRecordsArgs() interface{} {
	return &GetRecordsArgs{}
}

func newGetRecordsResult() interface{} {
	return &GetRecordsResult{}
}

type GetRecordsArgs struct {
	Req *karpo_persona.GetRecordsRequest
}

func (p *GetRecordsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetRecordsArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.GetRecordsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetRecordsArgs_Req_DEFAULT *karpo_persona.GetRecordsRequest

func (p *GetRecordsArgs) GetReq() *karpo_persona.GetRecordsRequest {
	if !p.IsSetReq() {
		return GetRecordsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetRecordsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetRecordsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetRecordsResult struct {
	Success *karpo_persona.GetRecordsResponse
}

var GetRecordsResult_Success_DEFAULT *karpo_persona.GetRecordsResponse

func (p *GetRecordsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetRecordsResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.GetRecordsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetRecordsResult) GetSuccess() *karpo_persona.GetRecordsResponse {
	if !p.IsSetSuccess() {
		return GetRecordsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetRecordsResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.GetRecordsResponse)
}

func (p *GetRecordsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetRecordsResult) GetResult() interface{} {
	return p.Success
}

func searchRecordsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.SearchRecordsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaEngineService).SearchRecords(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchRecordsArgs:
		success, err := handler.(karpo_persona.PersonaEngineService).SearchRecords(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchRecordsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchRecordsArgs() interface{} {
	return &SearchRecordsArgs{}
}

func newSearchRecordsResult() interface{} {
	return &SearchRecordsResult{}
}

type SearchRecordsArgs struct {
	Req *karpo_persona.SearchRecordsRequest
}

func (p *SearchRecordsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchRecordsArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.SearchRecordsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchRecordsArgs_Req_DEFAULT *karpo_persona.SearchRecordsRequest

func (p *SearchRecordsArgs) GetReq() *karpo_persona.SearchRecordsRequest {
	if !p.IsSetReq() {
		return SearchRecordsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchRecordsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchRecordsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchRecordsResult struct {
	Success *karpo_persona.SearchRecordsResponse
}

var SearchRecordsResult_Success_DEFAULT *karpo_persona.SearchRecordsResponse

func (p *SearchRecordsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchRecordsResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.SearchRecordsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchRecordsResult) GetSuccess() *karpo_persona.SearchRecordsResponse {
	if !p.IsSetSuccess() {
		return SearchRecordsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchRecordsResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.SearchRecordsResponse)
}

func (p *SearchRecordsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchRecordsResult) GetResult() interface{} {
	return p.Success
}

func getRecordSourcesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.GetRecordSourcesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaEngineService).GetRecordSources(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetRecordSourcesArgs:
		success, err := handler.(karpo_persona.PersonaEngineService).GetRecordSources(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetRecordSourcesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetRecordSourcesArgs() interface{} {
	return &GetRecordSourcesArgs{}
}

func newGetRecordSourcesResult() interface{} {
	return &GetRecordSourcesResult{}
}

type GetRecordSourcesArgs struct {
	Req *karpo_persona.GetRecordSourcesRequest
}

func (p *GetRecordSourcesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetRecordSourcesArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.GetRecordSourcesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetRecordSourcesArgs_Req_DEFAULT *karpo_persona.GetRecordSourcesRequest

func (p *GetRecordSourcesArgs) GetReq() *karpo_persona.GetRecordSourcesRequest {
	if !p.IsSetReq() {
		return GetRecordSourcesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetRecordSourcesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetRecordSourcesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetRecordSourcesResult struct {
	Success *karpo_persona.GetRecordSourcesResponse
}

var GetRecordSourcesResult_Success_DEFAULT *karpo_persona.GetRecordSourcesResponse

func (p *GetRecordSourcesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetRecordSourcesResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.GetRecordSourcesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetRecordSourcesResult) GetSuccess() *karpo_persona.GetRecordSourcesResponse {
	if !p.IsSetSuccess() {
		return GetRecordSourcesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetRecordSourcesResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.GetRecordSourcesResponse)
}

func (p *GetRecordSourcesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetRecordSourcesResult) GetResult() interface{} {
	return p.Success
}

func getRecordHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.GetRecordHistoryRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaEngineService).GetRecordHistory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetRecordHistoryArgs:
		success, err := handler.(karpo_persona.PersonaEngineService).GetRecordHistory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetRecordHistoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetRecordHistoryArgs() interface{} {
	return &GetRecordHistoryArgs{}
}

func newGetRecordHistoryResult() interface{} {
	return &GetRecordHistoryResult{}
}

type GetRecordHistoryArgs struct {
	Req *karpo_persona.GetRecordHistoryRequest
}

func (p *GetRecordHistoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetRecordHistoryArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.GetRecordHistoryRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetRecordHistoryArgs_Req_DEFAULT *karpo_persona.GetRecordHistoryRequest

func (p *GetRecordHistoryArgs) GetReq() *karpo_persona.GetRecordHistoryRequest {
	if !p.IsSetReq() {
		return GetRecordHistoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetRecordHistoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetRecordHistoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetRecordHistoryResult struct {
	Success *karpo_persona.GetRecordHistoryResponse
}

var GetRecordHistoryResult_Success_DEFAULT *karpo_persona.GetRecordHistoryResponse

func (p *GetRecordHistoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetRecordHistoryResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.GetRecordHistoryResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetRecordHistoryResult) GetSuccess() *karpo_persona.GetRecordHistoryResponse {
	if !p.IsSetSuccess() {
		return GetRecordHistoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetRecordHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.GetRecordHistoryResponse)
}

func (p *GetRecordHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetRecordHistoryResult) GetResult() interface{} {
	return p.Success
}

func getUserStatsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.GetUserStatsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaEngineService).GetUserStats(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserStatsArgs:
		success, err := handler.(karpo_persona.PersonaEngineService).GetUserStats(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserStatsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserStatsArgs() interface{} {
	return &GetUserStatsArgs{}
}

func newGetUserStatsResult() interface{} {
	return &GetUserStatsResult{}
}

type GetUserStatsArgs struct {
	Req *karpo_persona.GetUserStatsRequest
}

func (p *GetUserStatsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserStatsArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.GetUserStatsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserStatsArgs_Req_DEFAULT *karpo_persona.GetUserStatsRequest

func (p *GetUserStatsArgs) GetReq() *karpo_persona.GetUserStatsRequest {
	if !p.IsSetReq() {
		return GetUserStatsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserStatsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserStatsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserStatsResult struct {
	Success *karpo_persona.GetUserStatsResponse
}

var GetUserStatsResult_Success_DEFAULT *karpo_persona.GetUserStatsResponse

func (p *GetUserStatsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserStatsResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.GetUserStatsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserStatsResult) GetSuccess() *karpo_persona.GetUserStatsResponse {
	if !p.IsSetSuccess() {
		return GetUserStatsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.GetUserStatsResponse)
}

func (p *GetUserStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserStatsResult) GetResult() interface{} {
	return p.Success
}

func provisionUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(karpo_persona.ProvisionUserRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(karpo_persona.PersonaEngineService).ProvisionUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ProvisionUserArgs:
		success, err := handler.(karpo_persona.PersonaEngineService).ProvisionUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ProvisionUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newProvisionUserArgs() interface{} {
	return &ProvisionUserArgs{}
}

func newProvisionUserResult() interface{} {
	return &ProvisionUserResult{}
}

type ProvisionUserArgs struct {
	Req *karpo_persona.ProvisionUserRequest
}

func (p *ProvisionUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ProvisionUserArgs) Unmarshal(in []byte) error {
	msg := new(karpo_persona.ProvisionUserRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ProvisionUserArgs_Req_DEFAULT *karpo_persona.ProvisionUserRequest

func (p *ProvisionUserArgs) GetReq() *karpo_persona.ProvisionUserRequest {
	if !p.IsSetReq() {
		return ProvisionUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ProvisionUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProvisionUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ProvisionUserResult struct {
	Success *karpo_persona.ProvisionUserResponse
}

var ProvisionUserResult_Success_DEFAULT *karpo_persona.ProvisionUserResponse

func (p *ProvisionUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ProvisionUserResult) Unmarshal(in []byte) error {
	msg := new(karpo_persona.ProvisionUserResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ProvisionUserResult) GetSuccess() *karpo_persona.ProvisionUserResponse {
	if !p.IsSetSuccess() {
		return ProvisionUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ProvisionUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*karpo_persona.ProvisionUserResponse)
}

func (p *ProvisionUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProvisionUserResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) HealthCheck(ctx context.Context, Req *karpo_persona.HealthCheckRequest) (r *karpo_persona.HealthCheckResponse, err error) {
	var _args HealthCheckArgs
	_args.Req = Req
	var _result HealthCheckResult
	if err = p.c.Call(ctx, "HealthCheck", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Absorb(ctx context.Context, Req *karpo_persona.AbsorbRequest) (r *karpo_persona.AbsorbResponse, err error) {
	var _args AbsorbArgs
	_args.Req = Req
	var _result AbsorbResult
	if err = p.c.Call(ctx, "Absorb", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Recall(ctx context.Context, Req *karpo_persona.RecallRequest) (r *karpo_persona.RecallResponse, err error) {
	var _args RecallArgs
	_args.Req = Req
	var _result RecallResult
	if err = p.c.Call(ctx, "Recall", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserCategories(ctx context.Context, Req *karpo_persona.GetUserCategoriesRequest) (r *karpo_persona.GetUserCategoriesResponse, err error) {
	var _args GetUserCategoriesArgs
	_args.Req = Req
	var _result GetUserCategoriesResult
	if err = p.c.Call(ctx, "GetUserCategories", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserGraph(ctx context.Context, Req *karpo_persona.GetUserGraphRequest) (r *karpo_persona.GetUserGraphResponse, err error) {
	var _args GetUserGraphArgs
	_args.Req = Req
	var _result GetUserGraphResult
	if err = p.c.Call(ctx, "GetUserGraph", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TestPipeline(ctx context.Context, Req *karpo_persona.TestPipelineRequest) (r *karpo_persona.TestPipelineResponse, err error) {
	var _args TestPipelineArgs
	_args.Req = Req
	var _result TestPipelineResult
	if err = p.c.Call(ctx, "TestPipeline", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRecords(ctx context.Context, Req *karpo_persona.GetRecordsRequest) (r *karpo_persona.GetRecordsResponse, err error) {
	var _args GetRecordsArgs
	_args.Req = Req
	var _result GetRecordsResult
	if err = p.c.Call(ctx, "GetRecords", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchRecords(ctx context.Context, Req *karpo_persona.SearchRecordsRequest) (r *karpo_persona.SearchRecordsResponse, err error) {
	var _args SearchRecordsArgs
	_args.Req = Req
	var _result SearchRecordsResult
	if err = p.c.Call(ctx, "SearchRecords", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRecordSources(ctx context.Context, Req *karpo_persona.GetRecordSourcesRequest) (r *karpo_persona.GetRecordSourcesResponse, err error) {
	var _args GetRecordSourcesArgs
	_args.Req = Req
	var _result GetRecordSourcesResult
	if err = p.c.Call(ctx, "GetRecordSources", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRecordHistory(ctx context.Context, Req *karpo_persona.GetRecordHistoryRequest) (r *karpo_persona.GetRecordHistoryResponse, err error) {
	var _args GetRecordHistoryArgs
	_args.Req = Req
	var _result GetRecordHistoryResult
	if err = p.c.Call(ctx, "GetRecordHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserStats(ctx context.Context, Req *karpo_persona.GetUserStatsRequest) (r *karpo_persona.GetUserStatsResponse, err error) {
	var _args GetUserStatsArgs
	_args.Req = Req
	var _result GetUserStatsResult
	if err = p.c.Call(ctx, "GetUserStats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ProvisionUser(ctx context.Context, Req *karpo_persona.ProvisionUserRequest) (r *karpo_persona.ProvisionUserResponse, err error) {
	var _args ProvisionUserArgs
	_args.Req = Req
	var _result ProvisionUserResult
	if err = p.c.Call(ctx, "ProvisionUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
