// Code generated by Kitex v0.16.1. DO NOT EDIT.

package karpo_persona

import (
	"context"

	"github.com/cloudwego/prutal"
)

// Health check request.
type PersonaApiHealthCheckReq struct {
}

func (x *PersonaApiHealthCheckReq) Reset() { *x = PersonaApiHealthCheckReq{} }

func (x *PersonaApiHealthCheckReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *PersonaApiHealthCheckReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

// Health check response.
type PersonaApiHealthCheckResp struct {
	// Service health status, e.g. "ok".
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`

	// Service version string.
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (x *PersonaApiHealthCheckResp) Reset() { *x = PersonaApiHealthCheckResp{} }

func (x *PersonaApiHealthCheckResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *PersonaApiHealthCheckResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PersonaApiHealthCheckResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PersonaApiHealthCheckResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PersonaApiService interface {
	HealthCheck(ctx context.Context, req *PersonaApiHealthCheckReq) (res *PersonaApiHealthCheckResp, err error)
}
